/**
 * This file is automatically generated and should not be edited.
 *
 * To modify this file, please run the corresponding tool by calling either
 * "RequestFirebaseProjectWithConfig" or "UpdateFirebaseProjectTool" and
 * providing the desired configuration.
 */
import { FirebaseOptions } from "firebase/app";

export const firebaseConfig: FirebaseOptions = {
  "apiKey": "AIzaSyD_ZEhD-4avFJc1rA4BpXhEuDvb2rAW1NU",
  "authDomain": "hrms-af28f.firebaseapp.com",
  "projectId": "hrms-af28f",
  "storageBucket": "hrms-af28f.appspot.com",
  "messagingSenderId": "924905397621",
  "appId": "1:924905397621:web:8a4b7496d8e47b26e8873c",
  "measurementId": "G-FVP0C3XG1H"
};
