/**
 * This file is automatically generated and should not be edited.
 *
 * To modify this file, please run the corresponding tool by calling either
 * "RequestFirebaseProjectWithConfig" or "UpdateFirebaseProjectTool" and
 * providing the desired configuration.
 */
import { FirebaseOptions } from "firebase/app";

export const firebaseConfig: FirebaseOptions = {
  "apiKey": "API_KEY",
  "authDomain": "hrms-af28f.firebaseapp.com",
  "projectId": "hrms-af28f",
  "storageBucket": "hrms-af28f.appspot.com",
  "messagingSenderId": "975313936997",
  "appId": "1:975313936997:web:8032e36b8e3a47926e82a9",
  "measurementId": "G-M9V6Y1G1C1"
};
